name: CI/CD Workflow

on:
  push:
    branches:
      - main # Se activa cuando hay un push en la rama 'main'
  pull_request:
    branches:
      - main # Se activa al crear una pull request hacia 'main'

jobs:
  build:
    runs-on: ubuntu-latest # Sistema operativo donde se ejecutarán las acciones

    steps:
    # Configurar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Instalar dependencias (ejemplo para un proyecto Node.js)
    - name: Install dependencies
      run: npm install

    # Ejecutar pruebas (si tienes configuradas en el proyecto)
    - name: Run tests
      run: npm test

    # Compilar o preparar el proyecto (opcional)
    - name: Build project
      run: npm run build

    # Acción personalizada al realizar un push (puedes agregar más comandos)
    - name: Echo confirmation
      run: echo "Changes have been successfully integrated!"
